version: '3.6'
services:
    influxdb:
        image: influxdb:2.6.1
        container_name: influxdb
        restart: always
        environment:
            - INFLUXDB_DB=influx
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        ports:
            - '8086:8086'
        volumes:
            - influxdb_store:/var/lib/influxdb
    scraper:
        depends_on:
            - influxdb
        environment:
            - INFLUX_TOKEN=HEPtS2BL_jqdCUsbvvgukDvIoX_1JVp9HC2K2REcCjRZeoE9WerSeT6AuZi24bT3ZpDwY0dodlDqtKpSH-JzuA==
            - INFLUX_ORG=akaflieg
            - INFLUX_URL=http://influxdb:8086/
            - APRS_ADDR=aprs.glidernet.org:14580
            - APRS_LOGIN_STR=user xxx pass -1 vers xxx 0.0.0 filter b/FLRDDEF2E,FLRDD962D/FLRDDA434/FLRDD832E/FLRDF1465/FLRDD832A/FLRDDEEF7

        build:
            dockerfile: scraper.DOCKERFILE
volumes:
    influxdb_store:
