version: "3.6"
services:
  timescale:
    image: timescale/timescaledb-ha:pg17-arm64
    container_name: timescale
    restart: always
    environment:
      - POSTGRES_USER=timescale
      - POSTGRES_PASSWORD=timescale
      - POSTGRES_DB=timescale
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
volumes:
  timescale_data: {}
